module.exports = { 
  location_suggestions: 
   [ { id: 280,
       name: 'New York City, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 1,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 1000,
       name: 'Long Island, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 1,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 1012,
       name: 'Buffalo, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 1,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 1006,
       name: 'Hudson Valley, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 994,
       name: 'Westchester County, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 997,
       name: 'Albany, New York, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 1003,
       name: 'Rochester, New York, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 988,
       name: 'Syracuse, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 982,
       name: 'Binghamton, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' },
     { id: 1009,
       name: 'Utica, NY',
       country_id: 216,
       country_name: 'United States',
       should_experiment_with: 0,
       discovery_enabled: 0,
       has_new_ad_format: 0,
       is_state: 0,
       state_id: 103,
       state_name: 'New York State',
       state_code: 'NY' } ],
  status: 'success',
  has_more: 0,
  has_total: 0 };